# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import sys
import os
sys.path.insert(0, os.path.abspath('../src'))
from datetime import date
import importlib

# -- Project information -----------------------------------------------------

project = 'pycita'
mod = importlib.import_module(project)

author = mod.__author__
copyright = f'{date.today().year}, {author}.'

# The version info for the project you're documenting, acts as replacement
# for |version| and |release|, also used in various other places throughout
# the built documents.
#
# The short X.Y version.
version = mod.__version__
# The full version, including alpha/beta/rc tags.
release = mod.__version__

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx_autodoc_typehints',
    'sphinx.ext.viewcode',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.autosectionlabel',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

smartquotes = False

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see the
# documentation.
#

_font_family = '-apple-system,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Microsoft YaHei Mono,Source Han Sans SC,Noto Sans CJK SC,WenQuanYi Micro Hei,sans-serif;'
html_theme_options = {
    'description': mod.__description__,
    'body_max_width': 'auto',
    'page_width': '1200px',
    'sidebar_width': '300px',
    'caption_font_family': _font_family,
    'font_family': _font_family,
    'head_font_family': _font_family,
}

# -- Extension configuration -------------------------------------------------
autodoc_default_options = {
    # 'members': 'var1, var2',
    # 'member-order': 'bysource',
    'special-members': '__init__',
    # 'undoc-members': True,
    # 'exclude-members': '__weakref__'
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
